### ISSUE TITLE
Default units as a config

### ISSUE THREAD

**Issue by kameyer226** [yaq-project/yaqc-qtpy#16]
Idea was to allow the default units per daemon be specified as a configuration option so that they can be adjusted there but load in as such on launch.

**Comment by untzag** [comment]
I am against this idea in the pursuit of simplicity. I personally think that the usability gain is outweighed by the additional complexity of configuration. Fragile configuration options have been a problem in the past.

We did already introduce persistence for hidden state, so I can't make too strong of an argument. This would be similar in complexity.

I guess the main thing I want to share is that we were very intentional NOT to have features like these. There are downsides to adding features like this to complex graphical programs. But it's up to the community to weigh the benefits :smile:

**Comment by ksunden** [comment]
I agree with @untzag on this point.

**Comment by untzag** [comment]
Closed as wontfix.

**Comment by untzag** [comment]
Cool, I didn't know there were multiple types of closing issues now
